# Generated by Django 2.2.7 on 2019-11-14 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('basketball', models.BooleanField(default=False)),
                ('cricket', models.BooleanField(default=False)),
                ('football', models.BooleanField(default=False)),
                ('hockey', models.BooleanField(default=False)),
                ('netball', models.BooleanField(default=False)),
                ('rugby', models.BooleanField(default=False)),
                ('squash', models.BooleanField(default=False)),
                ('tennis', models.BooleanField(default=False)),
            ],
        ),
        migrations.AddField(
            model_name='post',
            name='number_of_players_needed',
            field=models.IntegerField(null=True),
        ),
    ]
