# Generated by Django 2.2.7 on 2019-11-19 16:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191115_1549'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='lat',
        ),
        migrations.RemoveField(
            model_name='post',
            name='lon',
        ),
    ]
