# Generated by Django 2.2.7 on 2019-11-14 11:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_auto_20191114_1112'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sport',
            name='basketball',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='cricket',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='football',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='hockey',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='netball',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='rugby',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='squash',
        ),
        migrations.RemoveField(
            model_name='sport',
            name='tennis',
        ),
        migrations.AddField(
            model_name='post',
            name='sport_name',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='posts', to='posts.Sport'),
        ),
        migrations.AddField(
            model_name='sport',
            name='sport_name',
            field=models.CharField(default='Basketball', max_length=50),
        ),
    ]
