# Generated by Django 2.2.7 on 2019-11-20 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_auto_20191119_1634'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='post_image',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='team_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
