# Generated by Django 2.2.7 on 2019-11-20 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_auto_20191120_1142'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='lat',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='post',
            name='lon',
            field=models.FloatField(null=True),
        ),
    ]
